<a href="https://colab.research.google.com/github/Supritha07/ML/blob/main/ml_Copy_of_Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%cd /content/drive/MyDrive/Colab Notebooks/Project Folder


/content/drive/MyDrive/Colab Notebooks/Project Folder


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
!python text.py mini_newsgroups

fetch data
data already downloaded
read data
filter data
comp.sys.ibm.pc.hardware split to train: 75, test: 25
comp.sys.mac.hardware split to train: 75, test: 25
talk.politics.misc split to train: 75, test: 25
sci.space split to train: 75, test: 25
sci.electronics split to train: 75, test: 25
sci.med split to train: 75, test: 25
rec.sport.baseball split to train: 75, test: 25
misc.forsale split to train: 75, test: 25
rec.autos split to train: 75, test: 25
rec.motorcycles split to train: 75, test: 25
rec.sport.hockey split to train: 75, test: 25
talk.politics.guns split to train: 75, test: 25
talk.politics.mideast split to train: 75, test: 25
comp.windows.x split to train: 75, test: 25
sci.crypt split to train: 75, test: 25
talk.religion.misc split to train: 75, test: 25
soc.religion.christian split to train: 75, test: 25
alt.atheism split to train: 75, test: 25
comp.graphics split to train: 75, test: 25
comp.os.ms-windows.misc split to train: 75, test: 25
encode labels
build tfidf
/usr

In [ ]:
!python t1.py mini_newsgroups

fetch data
data already downloaded
read data
filter data
talk.politics.misc split to train: 75, test: 25
sci.space split to train: 75, test: 25
talk.politics.guns split to train: 75, test: 25
talk.politics.mideast split to train: 75, test: 25
talk.religion.misc split to train: 75, test: 25
soc.religion.christian split to train: 75, test: 25
alt.atheism split to train: 75, test: 25
comp.graphics split to train: 75, test: 25
comp.os.ms-windows.misc split to train: 75, test: 25
comp.sys.ibm.pc.hardware split to train: 75, test: 25
comp.sys.mac.hardware split to train: 75, test: 25
comp.windows.x split to train: 75, test: 25
misc.forsale split to train: 75, test: 25
rec.autos split to train: 75, test: 25
rec.motorcycles split to train: 75, test: 25
rec.sport.baseball split to train: 75, test: 25
rec.sport.hockey split to train: 75, test: 25
sci.crypt split to train: 75, test: 25
sci.electronics split to train: 75, test: 25
sci.med split to train: 75, test: 25
encode labels
build tfidf
/usr

In [ ]:
!python t2.py mini_newsgroups

fetch data
data already downloaded
read data
filter data
talk.politics.misc split to train: 75, test: 25
sci.space split to train: 75, test: 25
talk.politics.guns split to train: 75, test: 25
talk.politics.mideast split to train: 75, test: 25
talk.religion.misc split to train: 75, test: 25
soc.religion.christian split to train: 75, test: 25
alt.atheism split to train: 75, test: 25
comp.graphics split to train: 75, test: 25
comp.os.ms-windows.misc split to train: 75, test: 25
comp.sys.ibm.pc.hardware split to train: 75, test: 25
comp.sys.mac.hardware split to train: 75, test: 25
comp.windows.x split to train: 75, test: 25
misc.forsale split to train: 75, test: 25
rec.autos split to train: 75, test: 25
rec.motorcycles split to train: 75, test: 25
rec.sport.baseball split to train: 75, test: 25
rec.sport.hockey split to train: 75, test: 25
sci.crypt split to train: 75, test: 25
sci.electronics split to train: 75, test: 25
sci.med split to train: 75, test: 25
encode labels
build tfidf
/usr

In [ ]:
!python t3.py mini_newsgroups

fetch data
data already downloaded
read data
filter data
talk.politics.misc split to train: 75, test: 25
sci.space split to train: 75, test: 25
talk.politics.guns split to train: 75, test: 25
talk.politics.mideast split to train: 75, test: 25
talk.religion.misc split to train: 75, test: 25
soc.religion.christian split to train: 75, test: 25
alt.atheism split to train: 75, test: 25
comp.graphics split to train: 75, test: 25
comp.os.ms-windows.misc split to train: 75, test: 25
comp.sys.ibm.pc.hardware split to train: 75, test: 25
comp.sys.mac.hardware split to train: 75, test: 25
comp.windows.x split to train: 75, test: 25
misc.forsale split to train: 75, test: 25
rec.autos split to train: 75, test: 25
rec.motorcycles split to train: 75, test: 25
rec.sport.baseball split to train: 75, test: 25
rec.sport.hockey split to train: 75, test: 25
sci.crypt split to train: 75, test: 25
sci.electronics split to train: 75, test: 25
sci.med split to train: 75, test: 25
encode labels
build tfidf
/usr

In [ ]:
!python t4.py mini_newsgroups

fetch data
data already downloaded
read data
filter data
talk.politics.misc split to train: 75, test: 25
sci.space split to train: 75, test: 25
talk.politics.guns split to train: 75, test: 25
talk.politics.mideast split to train: 75, test: 25
talk.religion.misc split to train: 75, test: 25
soc.religion.christian split to train: 75, test: 25
alt.atheism split to train: 75, test: 25
comp.graphics split to train: 75, test: 25
comp.os.ms-windows.misc split to train: 75, test: 25
comp.sys.ibm.pc.hardware split to train: 75, test: 25
comp.sys.mac.hardware split to train: 75, test: 25
comp.windows.x split to train: 75, test: 25
misc.forsale split to train: 75, test: 25
rec.autos split to train: 75, test: 25
rec.motorcycles split to train: 75, test: 25
rec.sport.baseball split to train: 75, test: 25
rec.sport.hockey split to train: 75, test: 25
sci.crypt split to train: 75, test: 25
sci.electronics split to train: 75, test: 25
sci.med split to train: 75, test: 25
encode labels
build tfidf
/usr

In [ ]:
!python t5.py mini_newsgroups

fetch data
data already downloaded
read data
filter data
talk.politics.misc split to train: 75, test: 25
sci.space split to train: 75, test: 25
talk.politics.guns split to train: 75, test: 25
talk.politics.mideast split to train: 75, test: 25
talk.religion.misc split to train: 75, test: 25
soc.religion.christian split to train: 75, test: 25
alt.atheism split to train: 75, test: 25
comp.graphics split to train: 75, test: 25
comp.os.ms-windows.misc split to train: 75, test: 25
comp.sys.ibm.pc.hardware split to train: 75, test: 25
comp.sys.mac.hardware split to train: 75, test: 25
comp.windows.x split to train: 75, test: 25
misc.forsale split to train: 75, test: 25
rec.autos split to train: 75, test: 25
rec.motorcycles split to train: 75, test: 25
rec.sport.baseball split to train: 75, test: 25
rec.sport.hockey split to train: 75, test: 25
sci.crypt split to train: 75, test: 25
sci.electronics split to train: 75, test: 25
sci.med split to train: 75, test: 25
encode labels
build tfidf
/usr

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
!python t6.py mini_newsgroups


fetch data
data already downloaded
read data
filter data
alt.atheism split to train: 75, test: 25
comp.graphics split to train: 75, test: 25
comp.os.ms-windows.misc split to train: 75, test: 25
comp.sys.ibm.pc.hardware split to train: 75, test: 25
comp.sys.mac.hardware split to train: 75, test: 25
comp.windows.x split to train: 75, test: 25
misc.forsale split to train: 75, test: 25
rec.autos split to train: 75, test: 25
rec.motorcycles split to train: 75, test: 25
rec.sport.baseball split to train: 75, test: 25
rec.sport.hockey split to train: 75, test: 25
sci.crypt split to train: 75, test: 25
sci.electronics split to train: 75, test: 25
sci.med split to train: 75, test: 25
sci.space split to train: 75, test: 25
soc.religion.christian split to train: 75, test: 25
talk.politics.guns split to train: 75, test: 25
talk.politics.mideast split to train: 75, test: 25
talk.politics.misc split to train: 75, test: 25
talk.religion.misc split to train: 75, test: 25
encode labels
build tfidf
/usr

In [ ]:
!python t6.py 20newsgroups

fetch data
data already downloaded
read data
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/folder/t6.py", line 123, in <module>
    data = reader.read(path)
  File "/content/drive/MyDrive/Colab Notebooks/folder/reader.py", line 260, in read
    text = f.read()
  File "/usr/lib/python3.10/encodings/latin_1.py", line 25, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
^C


In [ ]:
!pip install scikit-learn nltk


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!python benchmark.py 20newsgroups 10 100 1000




Loading 20 Newsgroups dataset...
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:409: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['doe', 'ha', 'wa'] not in stop_words.
  warnings.warn(
LinearSVC()
features:	10
train time: 0.2967s
test time:  0.0013s
f1-score:   0.2572
f1-score for '10': 0.5383
f1-score for '15': 0.1352
f1-score for '8': 0.5704
f1-score for '9': 0.0000
f1-score for '11': 0.7417
f1-score for '7': 0.6547
f1-score for '13': 0.0000
f1-score for '14': 0.0000
f1-score for '5': 0.0000
f1-score for '2': 0.5327
f1-score for '12': 0.0000
f1-score for '3': 0.0000
f1-score for '6': 0.6339
f1-score for '1': 0.0000
f1-score for '4': 0.0000
f1-score for '17': 0.5590
f1-score for '16': 0.3555
f1-score 

In [ ]:
!pip install scikit-learn numpy deap


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 4.1 MB/s eta 0:00:00


In [ ]:
!python svm_gen.py


Running Genetic Algorithm for Feature Selection...

Best Feature Subset:
[    2     3     5 ... 23356 23357 23358]

Running Classifiers with Selected Features...

Support Vector Machine (SVM):
F1-score: 0.91592517398969

K-Nearest Neighbors (K-NN):
F1-score: 0.8292699319902616

Naive Bayes:
F1-score: 0.7833336875890068

Decision Tree:
F1-score: 0.7799737097194882

Random Forest:
F1-score: 0.8838993927810667



In [ ]:
!python t7.py

Running Genetic Algorithm for Feature Selection...

Best Feature Subset:
[    0     1     2 ... 23356 23357 23359]

F1-score (SVM): 0.9335935973526269


In [ ]:
!pip install --upgrade scikit-learn scipy



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!python benchmark.py 20newsgroups 10 100 1000



Loading 20 Newsgroups dataset...
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:409: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['doe', 'ha', 'wa'] not in stop_words.
  warnings.warn(
SVC(kernel='linear', random_state=42)
features:	10
train time: 3.5148s
test time:  3.0361s
f1-score:   0.2304
f1-score for '10': 0.4792
f1-score for '15': 0.1291
f1-score for '8': 0.5494
f1-score for '9': 0.0000
f1-score for '11': 0.6282
f1-score for '7': 0.6362
f1-score for '13': 0.0000
f1-score for '14': 0.0000
f1-score for '5': 0.0000
f1-score for '2': 0.5758
f1-score for '12': 0.0000
f1-score for '3': 0.0000
f1-score for '6': 0.6184
f1-score for '1': 0.0000
f1-score for '4': 0.0000
f1-score for '17': 0.4800
f1-score 

In [ ]:
!python knn_gen.py

Running Genetic Algorithm for Feature Selection...

Best Feature Subset:
[    0     3     5 ... 23355 23356 23357]

Running Classifiers with Selected Features...

Support Vector Machine (SVM):
F1-score: 0.9055533958538761

K-Nearest Neighbors (KNN):
F1-score: 0.8606209751720587

Rocchio:
F1-score: 0.0

Naive Bayes:
F1-score: 0.779150822652149

CART:
F1-score: 0.8463820593962998

SVM with RBF Kernel:
F1-score: 0.9231378733681513

